import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Typography } from '@mui/material'
import Layout from './layout';
import { Header, About } from '@/container';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Olalekan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <Header/>
          <About/>
      </Layout>
    </>
  )
}
